# Generated by Django 2.2.3 on 2019-07-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190710_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email2',
            field=models.EmailField(default='hola@hotmail.com', max_length=254),
        ),
    ]
