# Generated by Django 2.2.3 on 2019-07-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='create',
            new_name='created',
        ),
    ]
